site:
    title: "Hyper.sh - How To"
    subtitle: "Hyper.sh How To"
    limit: 10
    theme: theme
    lang: en
    comment: hyperhqhowto
    # logo: "-/images/avatar.jpg"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    root: "/howto"

authors:
    hyper:
        name: "Hyper.sh"
        intro: ""
    Pierre Tardy:
        name: "Pierre Tardy"
        intro: ""

build:
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        mkdir -p ../../dist_tmp/howto
        cp -R ./ ../../dist_tmp/howto/.
